name: Build and Deploy doc sites
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          persist-credentials: false

      - name: Build and Deploy to gh_pages
        uses: KomodoPlatform/vuepress-deploy@1.0.1
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: ${{ github.repository }}
          TARGET_BRANCH: gh-pages
          CNAME: "docs.tokel.io"
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist/
